import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../lib/navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Afya yako</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
